name: Workflow for CI With github actions

on:
  push:
    branches:
      - master

env:
  baseUrl: https://localhost:3000


jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
        - name:  Checkout Code
          uses: actions/checkout@v4

        - name: Install Node
          uses: actions/setup-node@v4
          with:
            node-version: 20.x

        - name: Install Dependencies
          run: npm install

        - name: Build Project
          run: npm run build

        - name: Checkout typescript errors
          run: npm i -g typescript && tsc

        - name: Checkout Eslint errors
          run: npm run eslint

        - name: Launch Unit and Integration Tests
          run: npm run test

        - name: Save build data
          uses: actions/upload-artifact@v4
          with:
            name: build
            if-no-files-found: error
            path: build


  cypress-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:

         - name: Checkout Code
           uses: actions/checkout@v4

         - name: Download the build data
           uses: actions/download-artifact@v4
           with:
              name: build
              path: build


         - name: Cypress run test 
           uses: cypress-io/github-action@v6
           with:
            start: npm start
            browser: chrome
