name: Workflow for C.Delivery With github actions

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  #variables needed for publish
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/youtube_ecommerce_docker_image:latest

jobs:

  #Container registry is a registry for docker image of GITHUB
  push_image_to_container_regitry:
    name: Push Docker Image to Container Registry
    runs-on: ubuntu-latest
    
      #Required permissions to write and read and saved image on the registry
    permissions: 
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name:  Checkout Code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Log in the container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} #Set automatically
          password: ${{ secrets.GITHUB_TOKEN }} #generate automatically 


      - name: Extract metadata for docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with: 
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Publish
        run: |
              docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
              docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      